version: "3"

services:
  web:
    build: ./web
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - "./web:/code"
    entrypoint:
      - python
      - chatapp.py
